name: client
description: Secure Online Voting App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Network
  http: ^1.2.0

  # State Management
  provider: ^6.1.1

  # Cryptography
  crypto: ^3.0.3

  # Biometrics
  local_auth: ^2.1.8

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# ----------------------------------------------------------
# CONFIGURATION FOR APP ICON (Must be all the way to the left)
# ----------------------------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21